language: java
addons:
  sonarcloud:
    organization: crescoedge
    token:
      secure: NxBnO+ZuBbeZW2ZxYqezgGgtS9IOz615GLfs4dECiAdXiCrsqyMMfCg560x0JuD+8YWA5Av5NHVoND8f64bb0U2ZRLlDiyn0N3VD+sXbArqYzYtfIIXglJlmLpIk59kxwCtKyoCkxewchlaO/ADy8SqEY2MscvJ0UDTFqNFAHqWg+daMYDE79gosJEfiYjriNW9ralB5Dtj7CQgo0EFQbMMQNaDR7tIH0mgdk6gOGLNX+CaZCqAHrrRw7FaJFCya3v4jeduEzMC+ZCiqRSDeCJs+OXTEx4xBsOklVTFx0EejVcyQiNbohodXiDb69HPZjseHnrdIXESnHqd2W8Hjfc88mYI4nR/ZbkKDdR98lYikx0cX28dnkgCtKS7hT6KNbB5j1Ff1IK4PxbNW2TfZhllClDS33vbYCDyFfVMn7pqfpBmJbpghsgwY783RV3JFLYpFQQlujHeHJvWlP+XTd6ECOYwOC7cmVln2JJNkE3WF7bkzYTiGmZhvM7dLn6Idn9yED1QguTQdj6ZwvClioSSQc31mmxp41UyJ5PdHFT4+Aee/K58z8leWETEh5iZDoYHoZBAE2IyMuL/RJkvZrgzv7RFb3q+aRXkCIovI11LUKYOu+3/NVyX2DhwljQhos5Jb3jAah+17aGWha4BC/HAPjKdQMp+Zuxx6F2nqvRg=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
- mvn package bundle:bundle
- mvn deploy:deploy-file -Dfile=target/library-1.0-SNAPSHOT.jar -Durl=https://oss.sonatype.org/content/repositories/snapshots -DrepositoryId=ossrh -DpomFile=pom.xml --settings travis-settings.xml -DskipTests=true -B
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - SONATYPE_USERNAME=crescoedge
  - secure: obmZmb7Zfe7BIUOcNICZwutA2ZTzXbhM1yip7jP34MxtFAljL6r+mASUmQyFCogVazUANeqLs8n1uiob4JsjqgIHdBOfNnJ/oUfw2CQzgCuu2f+kwyUbe3T8EhI8miypYpqdG/4uhNw/RUgEauosXckrGXKLNnrwMOY4rCM/xRgrSAXYd94CBRv0OHaDPVqBRO+7Bgalc1Zmv5tpCrbe3v2G0Q5cnxHshlnW4R87KR5zR6nhXB3qQZvE3/p/nrASkJA2buCGZTe1MzJtQiCPAzl6yTj6sLkh0vT+oHMh3Up6Ndr2wrJGZ4xO+mvmauecjZSsFXA53+X4wCZl3Fw/W2ImIeyZMvT4FxxJRN/yd0DefE9TNOqEC/GpOJ2yHYmQ5vIqohmhBHPHLHVrJXosHj3YrqizlH3gWli3DUzex26SzZs45Vz6AqVT1JAkNVvzTQCzAm5ZBpw+gpQFiDvpp9nF9I7BBFrfPaGqkoF5cJHI8lB+QCq9xGgNCHEvehhJVI5cVZ5ox6Z6UCJLJX8bkMglCzXcFP+kFTcHTmDY9IpKZmigJZlr0aeXL1WD5P5f+XAVW7bCs9ZVFT4ncUIvCjWrdvo0FXXVaWFVm1Feuh/fOVN40KWN/aEX2I1OEVyNFQ3JA+NTeXNGp8wyzjc2Zwx3Oms8ANHcW9IkG5sNQC0=
