language: java
addons:
  sonarcloud:
    organization: crescoedge
    token:
      secure: "NxBnO+ZuBbeZW2ZxYqezgGgtS9IOz615GLfs4dECiAdXiCrsqyMMfCg560x0JuD+8YWA5Av5NHVoND8f64bb0U2ZRLlDiyn0N3VD+sXbArqYzYtfIIXglJlmLpIk59kxwCtKyoCkxewchlaO/ADy8SqEY2MscvJ0UDTFqNFAHqWg+daMYDE79gosJEfiYjriNW9ralB5Dtj7CQgo0EFQbMMQNaDR7tIH0mgdk6gOGLNX+CaZCqAHrrRw7FaJFCya3v4jeduEzMC+ZCiqRSDeCJs+OXTEx4xBsOklVTFx0EejVcyQiNbohodXiDb69HPZjseHnrdIXESnHqd2W8Hjfc88mYI4nR/ZbkKDdR98lYikx0cX28dnkgCtKS7hT6KNbB5j1Ff1IK4PxbNW2TfZhllClDS33vbYCDyFfVMn7pqfpBmJbpghsgwY783RV3JFLYpFQQlujHeHJvWlP+XTd6ECOYwOC7cmVln2JJNkE3WF7bkzYTiGmZhvM7dLn6Idn9yED1QguTQdj6ZwvClioSSQc31mmxp41UyJ5PdHFT4+Aee/K58z8leWETEh5iZDoYHoZBAE2IyMuL/RJkvZrgzv7RFb3q+aRXkCIovI11LUKYOu+3/NVyX2DhwljQhos5Jb3jAah+17aGWha4BC/HAPjKdQMp+Zuxx6F2nqvRg="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

