language: java
addons:
  sonarcloud:
    organization: crescoedge
    token:
      secure: NxBnO+ZuBbeZW2ZxYqezgGgtS9IOz615GLfs4dECiAdXiCrsqyMMfCg560x0JuD+8YWA5Av5NHVoND8f64bb0U2ZRLlDiyn0N3VD+sXbArqYzYtfIIXglJlmLpIk59kxwCtKyoCkxewchlaO/ADy8SqEY2MscvJ0UDTFqNFAHqWg+daMYDE79gosJEfiYjriNW9ralB5Dtj7CQgo0EFQbMMQNaDR7tIH0mgdk6gOGLNX+CaZCqAHrrRw7FaJFCya3v4jeduEzMC+ZCiqRSDeCJs+OXTEx4xBsOklVTFx0EejVcyQiNbohodXiDb69HPZjseHnrdIXESnHqd2W8Hjfc88mYI4nR/ZbkKDdR98lYikx0cX28dnkgCtKS7hT6KNbB5j1Ff1IK4PxbNW2TfZhllClDS33vbYCDyFfVMn7pqfpBmJbpghsgwY783RV3JFLYpFQQlujHeHJvWlP+XTd6ECOYwOC7cmVln2JJNkE3WF7bkzYTiGmZhvM7dLn6Idn9yED1QguTQdj6ZwvClioSSQc31mmxp41UyJ5PdHFT4+Aee/K58z8leWETEh5iZDoYHoZBAE2IyMuL/RJkvZrgzv7RFb3q+aRXkCIovI11LUKYOu+3/NVyX2DhwljQhos5Jb3jAah+17aGWha4BC/HAPjKdQMp+Zuxx6F2nqvRg=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
- mvn help:effective-settings --settings travis-settings.xml
- mvn bundle:bundle deploy --settings travis-settings.xml -DskipTests=true -B
env:
  global:
  - SONATYPE_USERNAME=crescoedge
  - secure: VoVpAgsoWcQiyQBZhTSMQRQOyzqEsSKoYSo4wluAeljAXHANLRwGteWcR9oaizOOl3+RleuWZ114Ebg60Q+8moh0SrjiP9gMOn6EnxepKCb/Ap/xjH6xE4HCmVB/6kq42mcpTV+1OWcgi/hvhgj3nZjYi+XLJOWVc3oLwz7bMJ31Qx3KJ3Ikt3Mo+TKUWtGVoQPSXtbHe0ypgmHTBCnwgnV3p21aLjE06wLssBuoJM/zm6Zt+ikKuG9/cOVLB21xlwfwxuFB5Gnp6iaalhLcvvWRe+QfjE1qx5oVWu5lI3EkQR40rW3lbDiW1L55vT2oQRgW5vWn6Cd0k2DYXiW2//8nPp0AgWCuHnBJY4M9oXRos7EXrwgrnoBnerk9cyzeqXhEaf1KJpmnV66ODphhllhNgilDA7nxCe/SyzFd9UM154Q/dt1J+aj96yLJQsPfPnSMgPWbnUPNiWVnKT2amm7EFtQoZKnt460q6r3t8QIm7WF1tCYp0jANTiwy+99NUZnLeB5afvsfQ6rPJf6/mG7nl5YBtaXToSpphdEiW3hnzt4LWZXBvPiE2qe5ySY9rFzNIQkC58tnQfG21Ew0MAfApOeIKR1m58IR6cl9/bjn7+SayBG0vYZsB84mGC8mfDXj63r2/uto9htXO/2JXNaExIQ7aB4lJ380+rYnQ7w=
